version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run --rm --volume $(pwd):/app --workdir /app rasa/rasa:1.10.10 data validate
      - run: docker run --volume $(pwd):/app --rm rasa/rasa:1.10.10 test